### ISSUE TITLE
Add a link to this Github repo on Docker.com

### ISSUE THREAD

**Issue by zedtux** [litaio/docker-ruby#4]
![screenshot from 2015-05-16 12 17 30](https://cloud.githubusercontent.com/assets/478564/7665729/7859d9de-fbc5-11e4-902f-a4c78651424a.png)

The docker.com page do no have a link to the github repo.

**Comment by jimmycuadra** [comment]
Updated the description! Thanks for the report.

**Comment by zedtux** [comment]
Well I was thinking of the following 

![screenshot from 2015-05-16 15 36 02](https://cloud.githubusercontent.com/assets/478564/7666307/49c2a27e-fbe1-11e4-9e86-a40239febd1c.png)

You can see [this repo](https://registry.hub.docker.com/u/zedtux/nginx-proxy/) for example

**Comment by jimmycuadra** [comment]
Those links only exist for "automated builds" which this image doesn't use, because the Docker Registry has a few annoying limitations that they have yet to fix. Pretty soon I will be moving all Lita's images over to quay.io where it will be automated from pushes to the GitHub repo.

**Comment by zedtux** [comment]
Alright, thank you.
